name: .NET Core

on: [push]

jobs:
  build:

    name: Build on node ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        platform: [linux-x64, win-x64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build StatementParser/StatementParser.sln --configuration Release

    - name: Publish with dotnet
      run: dotnet publish -r ${{matrix.platform}} --configuration Release --self-contained true StatementParser/StatementParser.sln
      
    - name: Publish artifacts to GitHub
      uses: actions/upload-artifact@v1
      with:
        name: StatementParserCLI
        path: StatementParser/StatementParserCLI/bin/Release/netcoreapp3.1/publish
